#!/bin/bash
set -e
# cd to self bash script directory
# cd $( dirname ${BASH_SOURCE[0]})
echo Running isort
uv run isort --profile black zcmds_win32
echo Running black
uv run black zcmds_win32
echo Running pylint zcmds_win32
uv run pylint zcmds_win32
echo Running mypy zcmds_win32
uv run mypy zcmds_win32
echo Linting complete!